const models = [
  // === Model: ADAN - NEW ICON === 
  {
    name: "Adan",
    gender: "Hombres",
    photo: "../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
    height: "6'1-1,85m",
    measurements: "W 30-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8/42",
    portfolio: [
      "../models/hombres/adan - new icon/book/full/adan book_01.webp",
      "../models/hombres/adan - new icon/book/full/adan book_02.webp",
      "../models/hombres/adan - new icon/book/full/adan book_03.webp",
      "../models/hombres/adan - new icon/book/full/adan book_04.webp",
      "../models/hombres/adan - new icon/book/full/adan book_05.webp",
      "../models/hombres/adan - new icon/book/full/adan book_06.webp",
      "../models/hombres/adan - new icon/book/full/adan book_07.webp",
      "../models/hombres/adan - new icon/book/full/adan book_08.webp",
      "../models/hombres/adan - new icon/book/full/adan book_09.webp",
      "../models/hombres/adan - new icon/book/full/adan book_10.webp",
      "../models/hombres/adan - new icon/book/full/adan book_11.webp",
      "../models/hombres/adan - new icon/book/full/adan book_12.webp",
      "../models/hombres/adan - new icon/book/full/adan book_13.webp",
      "../models/hombres/adan - new icon/book/full/adan book_14.webp",
      "../models/hombres/adan - new icon/book/full/adan book_15.webp",
      "../models/hombres/adan - new icon/book/full/adan book_16.webp",
      "../models/hombres/adan - new icon/book/full/adan book_17.webp",
      "../models/hombres/adan - new icon/book/full/adan book_18.webp",
      "../models/hombres/adan - new icon/book/full/adan book_19.webp",
      "../models/hombres/adan - new icon/book/full/adan book_20.webp",
      "../models/hombres/adan - new icon/book/full/adan book_21.webp",
      "../models/hombres/adan - new icon/book/full/adan book_22.webp",
      "../models/hombres/adan - new icon/book/full/adan book_23.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas2.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas3.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas4.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas5.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan6.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan7.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan8.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan9.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan10.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan11.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan12.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan13.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan14.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan15.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan16.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan17.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan18.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan19.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan20.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas21.webp",
      //"../models/hombres/adan - new icon/videos/video_adan_1.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_2.mp4",
      // "../models/hombres/adan - new icon/videos/video_adan_3.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_4.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_5.mp4",

      
    ],
    instagram: []
  }, // === End Model ===

  // === Model: AGUSTIN BEJOS - NEW ICON ===
  {
    name: "Agustin",
    gender: "Hombres",
    photo: "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__1.webp",
    height: "6'2-1,88m",
    measurements: "W 32.5-81cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "8.5/42",
    portfolio: [
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book1.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book2.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book3.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book4.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book5.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book6.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book7.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book8.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book9.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book10.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book11.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book12.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book13.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book14.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book15.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book16.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book17.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__1.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__2.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__3.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__4.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: ANGEL BRETT - NEW ICON ===
  {
    name: "Angel",
    gender: "Hombres",
    photo: "../models/hombres/angel brett - new icon/polas/mini/angel bret__1.webp",
    height: "6'1-1,85m",
    measurements: "31-74cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/42",
    portfolio: [
      "../models/hombres/angel brett - new icon/book/mini/angel bret book1.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book2.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book3.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book4.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book5.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book6.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book7.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book8.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book9.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book10.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book11.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book12.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book13.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book14.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book15.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book16.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book17.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book18.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book19.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book20.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book21.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book22.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book23.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book24.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book25.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book26.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book27.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book28.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book29.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book30.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book31.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__2.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__3.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__4.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__5.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__6.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: JORGE TIRADO -BLINK ===
  {
    name: "Jorge Tirado",
    gender: "Hombres",
    photo: "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_4.webp",
    height: "6'2-1,87m",
    measurements: "W 30-72cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "10.5/44",
    portfolio: [
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book1.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book2.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book3.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book4.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book5.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book6.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book7.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book8.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book9.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book10.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book11.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book13.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book14.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book15.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book16.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book17.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book18.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book22.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book20.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book21.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book19.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book23.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_1.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_2.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_3.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_4.webp",
    
    ],
    instagram: []
  }, // === End Model ===

  // === Model: JOSEPH BIZARRO ' BLINK ===
  {
    name: "Joseph Bizarro",
    gender: "Hombres",
    photo: "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__1.webp",
    height: "6'1-1,85m",
    measurements: "W 32-80cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "43",
    portfolio: [
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__1.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__2.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__3.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__4.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__5.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__6.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__7.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__8.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__9.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__10.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Kevin Rodriguez - Ceres ===
  {
    name: "Kevin Rodriguez",
    gender: "Hombres",
    photo: "../models/hombres/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    height: "6'2-1,88m",
    measurements: "W 30.5-77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/44",
    portfolio: [
      "../models/hombres/kevin rodriguez - ceres/book/mini/1-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/2-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/3-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/4-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/5-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/6-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/7-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/8-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/9-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/10-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/11-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/12-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/13-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/14-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/15-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/16-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: ROBBY POWERS - NEW ICON ===
  {
    name: "Robby Powers",
    gender: "Hombres",
    photo: "../models/hombres/robby powers - new icon/book/mini/robby powers__1.webp",
    height: "6'2-1,87.5m",
    measurements: "W 31-79cm",
    hair: "Brown",
    eyes: "Blue",
    shoe: "11.5/43",
    portfolio: [
      "../models/hombres/robby powers - new icon/book/mini/robby powers__1.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__2.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__3.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__4.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__5.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__6.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__7.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__8.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__9.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_1.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_2.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_3.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_4.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Salih Topcouglu ===
  {
    name: "Salih",
    gender: "Hombres",
    photo: "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
    height: "6'2-1,88m",
    measurements: "W 30.5-77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/43",
    portfolio: [
      "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book2.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book3.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book4.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book5.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book6.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book7.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book8.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book9.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book10.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book11.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book12.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book13.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book14.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book15.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book16.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book17.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book18.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book19.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book20.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book21.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book22.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book23.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book24.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book25.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book26.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book27.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book28.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book29.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book30.webp",
      "../models/hombres/salih topcouglu/polas/mini/salih polas.webp",
      //"../models/hombres/salih topcouglu/videos/salih_video1.mov",
      //"../models/hombres/salih topcouglu/videos/salih_video2.MP4",
      //"../models/hombres/salih topcouglu/videos/salih_video3.MP4",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Santiago Poggi - Ceres ===
  {
    name: "Santiago Poggi",
    gender: "Hombres",
    photo: "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
    height: "6'2-1,88m",
    measurements: "W 26-65cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "9/43",
    portfolio: [
      "../models/hombres/santiago poggi - ceres/book/mini/1-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/2-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/3-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/4-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/5-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/6-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/7-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/8-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/9-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/10-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/11-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/12-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/13-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/14-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/15-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/16-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/17-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/18-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/19-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/50-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/61-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/30-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/95-santiago-poggi-2025-ceres.webp",
      //"../models/hombres/santiago poggi - ceres/videos/santiago_poggi4.mp4",
      //"../models/hombres/santiago poggi - ceres/videos/santiago_poggi5.mp4",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Santiago Zezular ===
  {
    name: "Santiago Zezular",
    gender: "Hombres",
    photo: "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
    height: "6'1.5-1,87m",
    measurements: "W 29.5-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "11/45",
    portfolio: [
      "../models/hombres/santiago zezular - ceres/book/mini/1-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/2-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/3-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/4-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/5-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/6-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/7-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/8-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/9-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/10-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/11-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/12-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/13-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/14-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/16-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/17-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/18-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/19-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/20-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/21-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/22-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/23-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/24-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/1-santiago-zezular-compolaroid-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/2-santiago-zezular-compolaroid-ceres.webp",
      //"../models/hombres/santiago zezular - ceres/videos/santiago_zezular1.mp4",
      //"../models/hombres/santiago zezular - ceres/videos/santiago_zezular2.mp4",

    ],
    instagram: []
  }, // === End Model ===
];
