const models = [
    
  {
    name: "Lina",
    gender: "Mujeres",
    photo: "../models/mujeres/lina/polas/full/lina_polas (1).WEBP",
    height: "5'10-1,78m",
    measurements: "B 30-76cm W 23-58cm H 31.5-80cm",
    hair: "Light Brown",
    eyes: "Blue",
    shoe: "",
    portfolio: [
      "../models/mujeres/lina/book/full/lina_book (1).jpg",
      "../models/mujeres/lina/book/full/lina_book (2).jpg",
      "../models/mujeres/lina/book/full/lina_book (3).jpg",
      "../models/mujeres/lina/book/full/lina_book (4).jpg",
      "../models/mujeres/lina/book/full/lina_book (5).jpg",
      "../models/mujeres/lina/book/full/lina_book (6).jpg",
      "../models/mujeres/lina/book/full/lina_book (7).jpg",
      "../models/mujeres/lina/book/full/lina_book (8).jpg",
      "../models/mujeres/lina/book/full/lina_book (9).jpg",
      "../models/mujeres/lina/book/full/lina_book (10).jpg",
      "../models/mujeres/lina/book/full/lina_book (11).jpg",
      "../models/mujeres/lina/book/full/lina_book (12).jpg",
      "../models/mujeres/lina/book/full/lina_book (13).jpg",
      "../models/mujeres/lina/book/full/lina_book (14).jpg",
      "../models/mujeres/lina/book/full/lina_book (15).jpg",
      "../models/mujeres/lina/book/full/lina_book (16).jpg",
      "../models/mujeres/lina/book/full/lina_book (17).jpg",
      "../models/mujeres/lina/book/full/lina_book (18).jpg",
      "../models/mujeres/lina/book/full/lina_book (19).jpg",
      "../models/mujeres/lina/book/full/lina_book (20).jpg",
      "../models/mujeres/lina/book/full/lina_book (21).jpg",
      "../models/mujeres/lina/book/full/lina_book (22).jpg",
      "../models/mujeres/lina/book/full/lina_book (23).jpg",
      "../models/mujeres/lina/book/full/lina_book (24).jpg",
      "../models/mujeres/lina/book/full/lina_book (25).jpg",
      "../models/mujeres/lina/book/full/lina_book (26).jpg",
      "../models/mujeres/lina/book/full/lina_book (27).jpg",
      "../models/mujeres/lina/book/full/lina_book (28).jpg",
      "../models/mujeres/lina/book/full/lina_book (29).jpg",
      "../models/mujeres/lina/book/full/lina_book (30).jpg",
      "../models/mujeres/lina/book/full/lina_book (31).jpg",
      "../models/mujeres/lina/book/full/lina_book (32).jpg",
      "../models/mujeres/lina/book/full/lina_book (33).jpg",
      "../models/mujeres/lina/book/full/lina_book (34).jpg",
      "../models/mujeres/lina/book/full/lina_book (35).jpg",
      "../models/mujeres/lina/book/full/lina_book (36).jpg",
      "../models/mujeres/lina/book/full/lina_book (37).jpg",
      "../models/mujeres/lina/book/full/lina_book (38).jpg",
      "../models/mujeres/lina/polas/full/lina_polas (1).WEBP",
      "../models/mujeres/lina/polas/full/lina_polas (2).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (3).WEBP",
      "../models/mujeres/lina/polas/full/lina_polas (4).WEBP",
      "../models/mujeres/lina/polas/full/lina_polas (5).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (6).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (7).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (8).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (9).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (10).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (11).WEBP",
      "../models/mujeres/lina/polas/full/lina_polas (12).WEBP",
      //"../models/mujeres/lina/polas/full/lina_polas (13).WEBP",
    ]
  },
  
  // === Model: Mariana Arias ===
  {
    name: "Mariana Arias",
    gender: "Mujeres",
    photo: "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
    height: "5'9-1,75m",
    measurements: "B 29.5-75.5cm W 24-60cm H 34.5-88cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "7-38",
    portfolio: [
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_1.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_2.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_3.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_4.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_5.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_6.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_7.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_8.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_9.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_10.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_11.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_12.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_13.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_14.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_15.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_16.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_17.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_18.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_19.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_20.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_21.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_22.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_23.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_24.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_25.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_26.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_27.webp",
      "../models/mujeres/mariana-arias-new-icon/book/full/mariana_arias_book_28.webp",
      "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
      "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_2.jpg",
      "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_3.jpg",
      "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_4.jpg",
      "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_5.jpg",
     // "../models/mujeres/mariana-arias-new-icon/polas/full/mariana_arias_polas_6.jpg",
      //"../models/mujeres/mariana-arias-new-icon/videos/mariana_arias_video_1.mp4",
      //"../models/mujeres/mariana-arias-new-icon/videos/mariana_arias_video_2.mp4",
      //"../models/mujeres/mariana-arias-new-icon/videos/mariana_arias_video_3.mp4",
    ]
  },

  // === Model: Alicia Vallecilla ===
  {
    name: "Alicia Vallecilla",
    gender: "Mujeres",
    photo:  "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__1.webp",
    height: "5'8-1,75m",
    measurements: "B 30-75cm W 23-59cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/39",
    portfolio: [
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_01.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_02.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_03.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_05.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_06.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_07.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_08.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_09.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_10.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_11.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_12.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_13.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_14.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_15.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_16.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_17.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_18.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_19.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_20.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_21.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_22.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_23.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__1.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__2.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__3.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__4.webp",
    ]

  },

  // === Model: Audrey Coleman ===
  {
    name: "Audrey Coleman",
    gender: "Mujeres",
    photo: "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__4.webp",
    height: "5'9-1,76m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Light Brown",
    eyes: "Green",
    shoe: "7/38",
    portfolio: [
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 01.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 02.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 03.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 04.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 05.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 06.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 07.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 08.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 09.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 010.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 011.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 012.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 013.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 014.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__1.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__2.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__3.webp",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_01.mp4",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_02.mp4",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video03.mp4",
    ]
  },

  // === Model: Diana Zenteno ===
 /* {
    name: "Diana Zenteno",
    gender: "Mujeres",
    photo: "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6.5/38",
    portfolio: [
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book1.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book2.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book3.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book4.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book5.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book6.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book7.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book8.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book9.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book10.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book11.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book12.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book13.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book14.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book15.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book16.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book17.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book18.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book19.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book20.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book21.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__2.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__3.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__4.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__5.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__6.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__7.webp",
    ]

  },
*/
  // === Model: Felicitas Ceres ===
  {
    name: "Felicitas",
    gender: "Mujeres",
    photo: "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
    height: "5'9.5-1,76m",
    measurements: "B 32-81cm W 24-61cm H 38-96cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39.5",
    portfolio: [
        "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/2-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/3-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/4-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/5-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/6-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/7-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/8-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/9-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/10-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/11-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/12-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/13-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/14-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/15-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/16-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/17-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/18-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/19-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/20-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/21-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/22-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/23-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/24-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/1-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/10-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/18-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/20-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/26-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/31-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/37-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/42-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
    ]

  },

  // === Model: Fema Seimandi ===
  {
    name: "Fema Seimandi",
    gender: "Mujeres",
    photo: "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__1.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "7.5/38.5",
    portfolio: [
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book1.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book2.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book3.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book4.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book5.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book6.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book7.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book8.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book9.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book10.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book11.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book12.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book13.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book14.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book15.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book16.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book17.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book18.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book19.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book20.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book21.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book22.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book23.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book24.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__1.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__2.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__3.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__4.webp",
    ]

  },

  // === Model: Frida - Ceres ===
  {
    name: "Frida",
    gender: "Mujeres",
    photo: "../models/mujeres/frida - ceres/book/mini/1-frida-richter-main-book-ceres.webp",
    height: "5'9-1,75m",
    measurements: "B 32.5-82cm W 24-61cm H 36-91cm",
    hair: "Dark blond",
    eyes: "Blue",
    shoe: "9/40",
    portfolio: [
        "../models/mujeres/frida - ceres/book/mini/1-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/2-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/3-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/4-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/5-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/6-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/7-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/14-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/15-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/20-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/31-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/55-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/62-frida-richter-digitals-25-ceres.webp",
    ]

  },
  // === Model: Genesis - New Icon  ===
  {
    name: "Genesis",
    gender: "Mujeres",
    photo: "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
    height: "5'9.5-1,76m",
    measurements: "B 30.5-78cm W 24-60cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8/38",
    portfolio: [
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_01.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_02.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_03.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_04.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_05.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_06.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_07.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_08.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_09.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_10.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_11.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_12.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_13.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_14.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_15.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_16.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_17.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_18.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_19.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_20.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_21.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas2.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas3.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas4.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas5.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas6.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas7.webp",
      //"../models/mujeres/genesis  - new icon/videos/GENESIS-VIDEO-1.mp4",
    ]

  },

  // === Model: Kass - New Icon ===
  {

    name: "Kass",
    gender: "Mujeres",
    photo: "../models/mujeres/kass - new icon/book/mini/kass__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39",
    portfolio: [
      "../models/mujeres/kass - new icon/book/mini/kass__1.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__10.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__11.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__12.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__13.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__14.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__15.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__16.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__17.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__18.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__19.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__2.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__3.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__4.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__5.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__6.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__7.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__8.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__9.webp",
    ]

  },

  // === Model: Luciana Imoberdof - ARG ===
  {
    name: "Luciana Imoberdof",
    gender: "Mujeres",
    photo: "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 01.webp",
    height: "5'10-1,78m",
    measurements: "B 30-76cm W 24-60cm H 35-89cm",
    hair: "Blond",
    eyes: "Blue",
    shoe: "9/39",
    portfolio: [
      // Book
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book01.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book02.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book03.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book04.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book05.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book06.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book07.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book08.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book09.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book10.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book11.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book12.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book13.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book14.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book15.webp",
      // Polas
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 01.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 02.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 03.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 06.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 07.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 10.webp",

    ]

  },
 
  // === Model: Chloe - New Icon ===
  {
    name: "Chloe",
    gender: "Mujeres",
    photo: "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "5'9.5-1,75.5m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    portfolio: [
      "../models/mujeres/chloe - new icon/book/mini/chloe (1).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (2).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (3).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (4).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (5).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (6).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (7).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (8).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (9).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (10).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (11).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (12).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (13).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (14).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (15).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (16).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (17).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (18).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (19).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (20).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (21).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (22).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (23).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (24).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (25).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (26).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (27).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (28).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (29).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (30).webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola4.webp",
      //"../models/mujeres/chloe - new icon/videos/chloe_video (1).mov",
      //"../models/mujeres/chloe - new icon/videos/chloe_video (2).mov"
    ]

  },

    // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Mujeres",
    photo: "../models/mujeres/eva - gh/polas/mini/eva digitals 01.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 23-59cm H 35-89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    portfolio: [
      "../models/mujeres/eva - gh/book/mini/book01.webp",
      "../models/mujeres/eva - gh/book/mini/book02.webp",
      "../models/mujeres/eva - gh/book/mini/book03.webp",
      "../models/mujeres/eva - gh/book/mini/book04.webp",
      "../models/mujeres/eva - gh/book/mini/book05.webp",
      "../models/mujeres/eva - gh/book/mini/book06.webp",
      "../models/mujeres/eva - gh/book/mini/book07.webp",
      "../models/mujeres/eva - gh/book/mini/book08.webp",
      "../models/mujeres/eva - gh/book/mini/book09.webp",
      "../models/mujeres/eva - gh/book/mini/book010.webp",
      "../models/mujeres/eva - gh/book/mini/book011.webp",
      "../models/mujeres/eva - gh/book/mini/book013.webp",
      "../models/mujeres/eva - gh/book/mini/book014.webp",
      "../models/mujeres/eva - gh/book/mini/book015.webp",
      "../models/mujeres/eva - gh/book/mini/book016.webp",
      "../models/mujeres/eva - gh/book/mini/book017.webp",
      "../models/mujeres/eva - gh/book/mini/book018.webp",
      "../models/mujeres/eva - gh/book/mini/book019.webp",
      "../models/mujeres/eva - gh/book/mini/book020.webp",
      "../models/mujeres/eva - gh/book/mini/book021.webp",
      "../models/mujeres/eva - gh/book/mini/book022.webp",
      "../models/mujeres/eva - gh/book/mini/book023.webp",
      "../models/mujeres/eva - gh/book/mini/book024.webp",
      "../models/mujeres/eva - gh/book/mini/book025.webp",
      "../models/mujeres/eva - gh/book/mini/book026.webp",
      "../models/mujeres/eva - gh/book/mini/book027.webp",
      "../models/mujeres/eva - gh/book/mini/book028.webp",
      "../models/mujeres/eva - gh/book/mini/book029.webp",
      "../models/mujeres/eva - gh/book/mini/book030.webp",
      "../models/mujeres/eva - gh/book/mini/book031.webp",
      "../models/mujeres/eva - gh/book/mini/book032.webp",
      "../models/mujeres/eva - gh/book/mini/book033.webp",
      "../models/mujeres/eva - gh/book/mini/book034.webp",
      "../models/mujeres/eva - gh/book/mini/book035.webp",
      "../models/mujeres/eva - gh/book/mini/book036.webp",
      "../models/mujeres/eva - gh/book/mini/book037.webp",
      "../models/mujeres/eva - gh/book/mini/book038.webp",
      "../models/mujeres/eva - gh/book/mini/book039.webp",
      "../models/mujeres/eva - gh/book/mini/book040.webp",
      "../models/mujeres/eva - gh/book/mini/book041.webp",
      "../models/mujeres/eva - gh/book/mini/book042.webp",
      "../models/mujeres/eva - gh/book/mini/book043.webp",
      "../models/mujeres/eva - gh/book/mini/book044.webp",
      "../models/mujeres/eva - gh/book/mini/book045.webp",
      "../models/mujeres/eva - gh/book/mini/book046.webp",
      "../models/mujeres/eva - gh/book/mini/book047.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 01.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 02.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 03.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 04.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 05.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 06.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 07.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 08.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 09.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 10.webp",
      //"../models/mujeres/eva - gh/videos/eva_video1.mp4",
      //"../models/mujeres/eva - gh/videos/eva_video2.mp4",
    ]
  },
];
