const models = [

    // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Mujeres",
    photo: "../models/mujeres/eva - gh/polas/mini/eva digitals 01.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 23-59cm H 35-89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    download: "../models/mujeres/eva - gh/eva-full-material.zip",
    portfolio: [
      "../models/mujeres/eva - gh/book/mini/book01.webp",
      "../models/mujeres/eva - gh/book/mini/book02.webp",
      "../models/mujeres/eva - gh/book/mini/book03.webp",
      "../models/mujeres/eva - gh/book/mini/book04.webp",
      "../models/mujeres/eva - gh/book/mini/book05.webp",
      "../models/mujeres/eva - gh/book/mini/book06.webp",
      "../models/mujeres/eva - gh/book/mini/book07.webp",
      "../models/mujeres/eva - gh/book/mini/book08.webp",
      "../models/mujeres/eva - gh/book/mini/book09.webp",
      "../models/mujeres/eva - gh/book/mini/book010.webp",
      "../models/mujeres/eva - gh/book/mini/book011.webp",
      "../models/mujeres/eva - gh/book/mini/book013.webp",
      "../models/mujeres/eva - gh/book/mini/book014.webp",
      "../models/mujeres/eva - gh/book/mini/book015.webp",
      "../models/mujeres/eva - gh/book/mini/book016.webp",
      "../models/mujeres/eva - gh/book/mini/book017.webp",
      "../models/mujeres/eva - gh/book/mini/book018.webp",
      "../models/mujeres/eva - gh/book/mini/book019.webp",
      "../models/mujeres/eva - gh/book/mini/book020.webp",
      "../models/mujeres/eva - gh/book/mini/book021.webp",
      "../models/mujeres/eva - gh/book/mini/book022.webp",
      "../models/mujeres/eva - gh/book/mini/book023.webp",
      "../models/mujeres/eva - gh/book/mini/book024.webp",
      "../models/mujeres/eva - gh/book/mini/book025.webp",
      "../models/mujeres/eva - gh/book/mini/book026.webp",
      "../models/mujeres/eva - gh/book/mini/book027.webp",
      "../models/mujeres/eva - gh/book/mini/book028.webp",
      "../models/mujeres/eva - gh/book/mini/book029.webp",
      "../models/mujeres/eva - gh/book/mini/book030.webp",
      "../models/mujeres/eva - gh/book/mini/book031.webp",
      "../models/mujeres/eva - gh/book/mini/book032.webp",
      "../models/mujeres/eva - gh/book/mini/book033.webp",
      "../models/mujeres/eva - gh/book/mini/book034.webp",
      "../models/mujeres/eva - gh/book/mini/book035.webp",
      "../models/mujeres/eva - gh/book/mini/book036.webp",
      "../models/mujeres/eva - gh/book/mini/book037.webp",
      "../models/mujeres/eva - gh/book/mini/book038.webp",
      "../models/mujeres/eva - gh/book/mini/book039.webp",
      "../models/mujeres/eva - gh/book/mini/book040.webp",
      "../models/mujeres/eva - gh/book/mini/book041.webp",
      "../models/mujeres/eva - gh/book/mini/book042.webp",
      "../models/mujeres/eva - gh/book/mini/book043.webp",
      "../models/mujeres/eva - gh/book/mini/book044.webp",
      "../models/mujeres/eva - gh/book/mini/book045.webp",
      "../models/mujeres/eva - gh/book/mini/book046.webp",
      "../models/mujeres/eva - gh/book/mini/book047.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 01.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 02.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 03.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 04.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 05.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 06.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 07.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 08.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 09.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 10.webp",
      "../models/mujeres/eva - gh/videos/eva_video1.mp4",
      "../models/mujeres/eva - gh/videos/eva_video2.mp4",
    ]
    
  },

];
