const models = [
// === Model: Felicitas Ceres ===
  {
    name: "Felicitas",
    gender: "Mujeres",
    photo: "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
    height: "5'9.5-1,76m",
    measurements: "B 32-81cm W 24-61cm H 38-96cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39.5",
    download: "../models/mujeres/felicitas - ceres/felicitas full material.zip",
    portfolio: [
        "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/2-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/3-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/4-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/5-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/6-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/7-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/8-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/9-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/10-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/11-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/12-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/13-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/14-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/15-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/16-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/17-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/18-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/19-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/20-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/21-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/22-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/23-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/24-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/1-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/10-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/18-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/20-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/26-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/31-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/37-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/42-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/videos/felicitas_codesal_video_1.mp4",
        "../models/mujeres/felicitas - ceres/videos/felicitas_codesal_video_2.mp4",
        "../models/mujeres/felicitas - ceres/videos/felicitas_codesal_video_3.mp4",

    ]
    
  },
]