const models = [
 
  // === Model: Salih Topcouglu ===
  {
    name: "Salih",
    gender: "Hombres",
    photo: "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
    height: "6'2-1,88m",
    measurements: "W 30.5-77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/43",
    download: "../models/hombres/salih topcouglu/Salih-full-material.zip",
    portfolio: [
      "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book2.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book3.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book4.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book5.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book6.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book7.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book8.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book9.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book10.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book11.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book12.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book13.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book14.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book15.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book16.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book17.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book18.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book19.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book20.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book21.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book22.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book23.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book24.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book25.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book26.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book27.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book28.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book29.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book30.webp",
      "../models/hombres/salih topcouglu/polas/mini/salih polas.webp",
      "../models/hombres/salih topcouglu/videos/salih_video1.mov",
      "../models/hombres/salih topcouglu/videos/salih_video2.MP4",
      "../models/hombres/salih topcouglu/videos/salih_video3.MP4",
    ],
    instagram: []
  }, // === End Model ===
  
// === Model: Santiago Poggi - Ceres ===
  {
    name: "Santiago Poggi",
    gender: "Hombres",
    photo: "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
    height: "6'2-1,88m",
    measurements: "W 26-65cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "9/43",
    download: "../models/hombres/santiago poggi - ceres/Santiago-Poggi-full-material.zip",
    portfolio: [
      "../models/hombres/santiago poggi - ceres/book/mini/1-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/2-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/3-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/4-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/5-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/6-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/7-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/8-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/9-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/10-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/11-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/12-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/13-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/14-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/15-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/16-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/17-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/18-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/19-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/50-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/61-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/30-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/95-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/videos/santiago_poggi2.mp4",
      "../models/hombres/santiago poggi - ceres/videos/santiago_poggi3.mp4",
      "../models/hombres/santiago poggi - ceres/videos/santiago_poggi4.mp4",
      "../models/hombres/santiago poggi - ceres/videos/santiago_poggi5.mp4",
    ],
    instagram: []
  }, // === End Model ===


    // === Model: Santiago Zezular ===
  {
    name: "Santiago Zezular",
    gender: "Hombres",
    photo: "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
    height: "6'1.5-1,87m",
    measurements: "W 29.5-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "11/45",
    download: "../models/hombres/santiago zezular - ceres/Santiago-Zezular-full-material.zip",
    portfolio: [
      "../models/hombres/santiago zezular - ceres/book/mini/1-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/2-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/3-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/4-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/5-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/6-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/7-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/8-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/9-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/10-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/11-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/12-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/13-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/14-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/16-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/17-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/18-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/19-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/20-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/21-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/22-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/23-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/24-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/1-santiago-zezular-compolaroid-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/2-santiago-zezular-compolaroid-ceres.webp",
      "../models/hombres/santiago zezular - ceres/videos/santiago_zezular1.mp4",
      "../models/hombres/santiago zezular - ceres/videos/santiago_zezular2.mp4",
      "../models/hombres/santiago zezular - ceres/videos/santiago_zezular3.mp4",
      "../models/hombres/santiago zezular - ceres/videos/santiago_zezular4.mp4",
    ],
    instagram: []
  }, // === End Model ===


// === Model: Audrey Coleman ===
  {
    name: "Audrey Coleman",
    gender: "Mujeres",
    photo: "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__4.webp",
    height: "5'9-1,76m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Light Brown",
    eyes: "Green",
    shoe: "7/38",
    download: "../models/mujeres/audrey coleman - new icon/audrey-coleman-full.zip",
    portfolio: [
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 01.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 02.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 03.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 04.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 05.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 06.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 07.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 08.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 09.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 010.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 011.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 012.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 013.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 014.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__1.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__2.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__3.webp",
      "../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_01.mp4",
      "../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_02.mp4",
      "../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video03.mp4",
    ]

  },


// === Model: Genesis - New Icon  ===
  {
    name: "Genesis",
    gender: "Mujeres",
    photo: "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
    height: "5'9.5-1,76m",
    measurements: "B 30.5-78cm W 24-60cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8/38",
    download: "../models/mujeres/genesis  - new icon/genesis  - new icon.zip",
    portfolio: [
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_01.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_02.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_03.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_04.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_05.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_06.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_07.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_08.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_09.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_10.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_11.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_12.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_13.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_14.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_15.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_16.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_17.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_18.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_19.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_20.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_21.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas2.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas3.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas4.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas5.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas6.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas7.webp",
    ]

  },

  // === Model: Chloe - New Icon ===
  {
    name: "Chloe",
    gender: "Mujeres",
    photo: "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "5'9.5-1,75.5m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    download: "../models/mujeres/chloe - new icon/chloe-full.zip",
    portfolio: [
      "../models/mujeres/chloe - new icon/book/mini/chloe (1).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (2).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (3).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (4).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (5).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (6).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (7).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (8).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (9).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (10).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (11).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (12).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (13).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (14).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (15).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (16).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (17).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (18).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (19).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (20).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (21).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (22).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (23).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (24).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (25).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (26).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (27).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (28).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (29).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (30).webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola4.webp",
      "../models/mujeres/chloe - new icon/videos/chloe_video (1).mov",
      "../models/mujeres/chloe - new icon/videos/chloe_video (2).mov"
    ]
    
  },

  // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Mujeres",
    photo: "../models/mujeres/eva - gh/polas/mini/eva digitals 01.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 23-59cm H 35-89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    download: "../models/mujeres/eva - gh/eva-full-material.zip",
    portfolio: [
      "../models/mujeres/eva - gh/book/mini/book01.webp",
      "../models/mujeres/eva - gh/book/mini/book02.webp",
      "../models/mujeres/eva - gh/book/mini/book03.webp",
      "../models/mujeres/eva - gh/book/mini/book04.webp",
      "../models/mujeres/eva - gh/book/mini/book05.webp",
      "../models/mujeres/eva - gh/book/mini/book06.webp",
      "../models/mujeres/eva - gh/book/mini/book07.webp",
      "../models/mujeres/eva - gh/book/mini/book08.webp",
      "../models/mujeres/eva - gh/book/mini/book09.webp",
      "../models/mujeres/eva - gh/book/mini/book010.webp",
      "../models/mujeres/eva - gh/book/mini/book011.webp",
      "../models/mujeres/eva - gh/book/mini/book013.webp",
      "../models/mujeres/eva - gh/book/mini/book014.webp",
      "../models/mujeres/eva - gh/book/mini/book015.webp",
      "../models/mujeres/eva - gh/book/mini/book016.webp",
      "../models/mujeres/eva - gh/book/mini/book017.webp",
      "../models/mujeres/eva - gh/book/mini/book018.webp",
      "../models/mujeres/eva - gh/book/mini/book019.webp",
      "../models/mujeres/eva - gh/book/mini/book020.webp",
      "../models/mujeres/eva - gh/book/mini/book021.webp",
      "../models/mujeres/eva - gh/book/mini/book022.webp",
      "../models/mujeres/eva - gh/book/mini/book023.webp",
      "../models/mujeres/eva - gh/book/mini/book024.webp",
      "../models/mujeres/eva - gh/book/mini/book025.webp",
      "../models/mujeres/eva - gh/book/mini/book026.webp",
      "../models/mujeres/eva - gh/book/mini/book027.webp",
      "../models/mujeres/eva - gh/book/mini/book028.webp",
      "../models/mujeres/eva - gh/book/mini/book029.webp",
      "../models/mujeres/eva - gh/book/mini/book030.webp",
      "../models/mujeres/eva - gh/book/mini/book031.webp",
      "../models/mujeres/eva - gh/book/mini/book032.webp",
      "../models/mujeres/eva - gh/book/mini/book033.webp",
      "../models/mujeres/eva - gh/book/mini/book034.webp",
      "../models/mujeres/eva - gh/book/mini/book035.webp",
      "../models/mujeres/eva - gh/book/mini/book036.webp",
      "../models/mujeres/eva - gh/book/mini/book037.webp",
      "../models/mujeres/eva - gh/book/mini/book038.webp",
      "../models/mujeres/eva - gh/book/mini/book039.webp",
      "../models/mujeres/eva - gh/book/mini/book040.webp",
      "../models/mujeres/eva - gh/book/mini/book041.webp",
      "../models/mujeres/eva - gh/book/mini/book042.webp",
      "../models/mujeres/eva - gh/book/mini/book043.webp",
      "../models/mujeres/eva - gh/book/mini/book044.webp",
      "../models/mujeres/eva - gh/book/mini/book045.webp",
      "../models/mujeres/eva - gh/book/mini/book046.webp",
      "../models/mujeres/eva - gh/book/mini/book047.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 01.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 02.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 03.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 04.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 05.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 06.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 07.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 08.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 09.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 10.webp",
      "../models/mujeres/eva - gh/videos/eva_video1.mp4",
      "../models/mujeres/eva - gh/videos/eva_video2.mp4",
      "../models/mujeres/eva - gh/videos/eva_video3.mp4",
    ]
    
  },
];
