const models = [
 
  // === Model: Diana Zenteno ===
  {
    name: "Diana Zenteno",
    gender: "Mujeres",
    photo: "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6.5/38",
    download: "../models/mujeres/diana zenteno - new icon/diana-full-material.zip",
    portfolio: [
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book1.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book2.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book3.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book4.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book5.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book6.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book7.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book8.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book9.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book10.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book11.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book12.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book13.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book14.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book15.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book16.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book17.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book18.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book19.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book20.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book21.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__2.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__3.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__4.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__5.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__6.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__7.webp",
    ]
    
  },
 
  // === Model: ADAN - NEW ICON === 
  {
    name: "Adan",
    gender: "Hombres",
    photo: "../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
    height: "6'1-1,85m",
    measurements: "W 30-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8/42",
    download: "../models/hombres/adan - new icon/adan-full-material.zip",
    portfolio: [
      "../models/hombres/adan - new icon/book/full/adan book_01.webp",
      "../models/hombres/adan - new icon/book/full/adan book_02.webp",
      "../models/hombres/adan - new icon/book/full/adan book_03.webp",
      "../models/hombres/adan - new icon/book/full/adan book_04.webp",
      "../models/hombres/adan - new icon/book/full/adan book_05.webp",
      "../models/hombres/adan - new icon/book/full/adan book_06.webp",
      "../models/hombres/adan - new icon/book/full/adan book_07.webp",
      "../models/hombres/adan - new icon/book/full/adan book_08.webp",
      "../models/hombres/adan - new icon/book/full/adan book_09.webp",
      "../models/hombres/adan - new icon/book/full/adan book_10.webp",
      "../models/hombres/adan - new icon/book/full/adan book_11.webp",
      "../models/hombres/adan - new icon/book/full/adan book_12.webp",
      "../models/hombres/adan - new icon/book/full/adan book_13.webp",
      "../models/hombres/adan - new icon/book/full/adan book_14.webp",
      "../models/hombres/adan - new icon/book/full/adan book_15.webp",
      "../models/hombres/adan - new icon/book/full/adan book_16.webp",
      "../models/hombres/adan - new icon/book/full/adan book_17.webp",
      "../models/hombres/adan - new icon/book/full/adan book_18.webp",
      "../models/hombres/adan - new icon/book/full/adan book_19.webp",
      "../models/hombres/adan - new icon/book/full/adan book_20.webp",
      "../models/hombres/adan - new icon/book/full/adan book_21.webp",
      "../models/hombres/adan - new icon/book/full/adan book_22.webp",
      "../models/hombres/adan - new icon/book/full/adan book_23.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas2.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas3.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas4.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas5.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan6.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan7.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan8.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan9.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan10.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan11.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan12.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan13.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan14.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan15.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan16.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan17.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan18.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan19.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan20.webp",
      "../models/hombres/adan - new icon/videos/video_adan_1.mp4",
      "../models/hombres/adan - new icon/videos/video_adan_2.mp4",
      "../models/hombres/adan - new icon/videos/video_adan_3.mp4",
      "../models/hombres/adan - new icon/videos/video_adan_4.mp4",
      "../models/hombres/adan - new icon/videos/video_adan_5.mp4",

      
    ],
    instagram: []
  }, // === End Model ===

  
  // === Model: Chloe - New Icon ===
  {
    name: "Chloe",
    gender: "Mujeres",
    photo: "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "5'9.5-1,75.5m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    download: "../models/mujeres/chloe - new icon/chloe-full.zip",
    portfolio: [
      "../models/mujeres/chloe - new icon/book/mini/chloe (1).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (2).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (3).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (4).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (5).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (6).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (7).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (8).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (9).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (10).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (11).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (12).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (13).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (14).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (15).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (16).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (17).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (18).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (19).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (20).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (21).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (22).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (23).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (24).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (25).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (26).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (27).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (28).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (29).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (30).webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola4.webp",
      "../models/mujeres/chloe - new icon/videos/chloe_video (1).mov",
      "../models/mujeres/chloe - new icon/videos/chloe_video (2).mov"
    ]
    
  },


];
