const models = [
 
  // === Model: Diana Zenteno ===
  {
    name: "Diana Zenteno",
    gender: "Mujeres",
    photo: "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6.5/38",
    download: "../models/mujeres/diana zenteno - new icon/diana-full-material.zip",
    portfolio: [
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book1.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book2.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book3.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book4.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book5.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book6.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book7.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book8.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book9.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book10.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book11.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book12.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book13.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book14.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book15.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book16.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book17.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book18.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book19.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book20.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book21.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__2.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__3.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__4.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__5.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__6.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__7.webp",
    ]
    
  },
];
