const models = [
  // === Model: ADAN - NEW ICON ===
  {
    name: "Adan",
    gender: "Hombres",
    photo: "../models/boys/adan - new icon/polas/mini/adan_polas 1.webp",
    height: "1.85m",
    measurements: "W 75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8/42",
    portfolio: [
      "../models/boys/adan - new icon/book/mini/adan book_01.webp",
      "../models/boys/adan - new icon/book/mini/adan book_02.webp",
      "../models/boys/adan - new icon/book/mini/adan book_03.webp",
      "../models/boys/adan - new icon/book/mini/adan book_04.webp",
      "../models/boys/adan - new icon/book/mini/adan book_05.webp",
      "../models/boys/adan - new icon/book/mini/adan book_06.webp",
      "../models/boys/adan - new icon/book/mini/adan book_07.webp",
      "../models/boys/adan - new icon/book/mini/adan book_08.webp",
      "../models/boys/adan - new icon/book/mini/adan book_09.webp",
      "../models/boys/adan - new icon/book/mini/adan book_10.webp",
      "../models/boys/adan - new icon/book/mini/adan book_11.webp",
      "../models/boys/adan - new icon/book/mini/adan book_12.webp",
      "../models/boys/adan - new icon/book/mini/adan book_13.webp",
      "../models/boys/adan - new icon/book/mini/adan book_14.webp",
      "../models/boys/adan - new icon/book/mini/adan book_15.webp",
      "../models/boys/adan - new icon/book/mini/adan book_16.webp",
      "../models/boys/adan - new icon/book/mini/adan book_17.webp",
      "../models/boys/adan - new icon/book/mini/adan book_18.webp",
      "../models/boys/adan - new icon/book/mini/adan book_19.webp",
      "../models/boys/adan - new icon/book/mini/adan book_20.webp",
      "../models/boys/adan - new icon/book/mini/adan book_21.webp",
      "../models/boys/adan - new icon/book/mini/adan book_22.webp",
      "../models/boys/adan - new icon/book/mini/adan book_23.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas 1.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas2.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas3.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas4.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas5.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan6.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan7.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan8.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan9.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan10.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan11.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan12.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan13.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan14.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan15.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan16.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan17.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan18.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan19.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan20.webp",
      "../models/boys/adan - new icon/polas/mini/adan_polas21.webp",
      //"../models/boys/adan - new icon/videos/video_adan_1.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_2.mp4",
      // "../models/boys/adan - new icon/videos/video_adan_3.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_4.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_5.mp4",


    ],
    instagram: []
  }, // === End Model ===

  // === Model: Alan Marquez ===
  {
    name: "Alan Marquez",
    gender: "Hombres",
    photo: "../models/boys/alan marquez/book/full/alan_marquez_book_01.jpg",
    measurements: "Suit 38L",
    hair: "Brown",
    eyes: "Green",
    shoe: "8/42",
    portfolio: [
      "../models/boys/alan marquez/book/full/alan_marquez_book_01.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_010.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_011.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_012.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_013.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_014.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_015.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_016.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_017.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_018.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_019.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_02.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_020.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_021.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_022.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_023.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_024.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_025.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_026.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_027.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_028.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_029.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_03.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_030.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_04.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_05.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_06.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_07.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_08.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_09.jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (1).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (2).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (3).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (4).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (5).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (6).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (7).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (8).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (9).jpg",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: ANGEL BRETT - NEW ICON ===
  {
    name: "Angel",
    gender: "Hombres",
    photo: "../models/boys/angel brett - new icon/polas/mini/angel bret__1.webp",
    height: "1.85m",
    measurements: "74cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/42",
    portfolio: [
      "../models/boys/angel brett - new icon/book/mini/angel bret book1.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book3.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book4.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book5.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book6.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book7.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book8.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book9.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book10.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book11.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book12.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book13.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book14.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book15.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book16.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book17.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book18.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book19.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book20.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book21.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book22.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book23.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book24.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book25.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book26.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book27.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book28.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book29.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book30.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book31.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__2.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__3.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__4.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__5.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__6.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Kevin Rodriguez - Ceres ===
  {
    name: "Kevin Rodriguez",
    gender: "Hombres",
    photo: "../models/boys/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    height: "1.88m",
    measurements: "W 77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/44",
    portfolio: [
      "../models/boys/kevin rodriguez - ceres/book/mini/1-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/2-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/3-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/4-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/5-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/6-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/7-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/8-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/9-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/10-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/11-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/12-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/13-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/14-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/15-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/16-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Salih Topcouglu ===
  {
    name: "Salih",
    gender: "Hombres",
    photo: "../models/boys/salih topcouglu/book/mini/salih book1.webp",
    height: "1.88m",
    measurements: "W 77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/43",
    portfolio: [
      "../models/boys/salih topcouglu/book/mini/salih book1.webp",
      "../models/boys/salih topcouglu/book/mini/salih book2.webp",
      "../models/boys/salih topcouglu/book/mini/salih book3.webp",
      "../models/boys/salih topcouglu/book/mini/salih book4.webp",
      "../models/boys/salih topcouglu/book/mini/salih book5.webp",
      "../models/boys/salih topcouglu/book/mini/salih book6.webp",
      "../models/boys/salih topcouglu/book/mini/salih book7.webp",
      "../models/boys/salih topcouglu/book/mini/salih book8.webp",
      "../models/boys/salih topcouglu/book/mini/salih book9.webp",
      "../models/boys/salih topcouglu/book/mini/salih book10.webp",
      "../models/boys/salih topcouglu/book/mini/salih book11.webp",
      "../models/boys/salih topcouglu/book/mini/salih book12.webp",
      "../models/boys/salih topcouglu/book/mini/salih book13.webp",
      "../models/boys/salih topcouglu/book/mini/salih book14.webp",
      "../models/boys/salih topcouglu/book/mini/salih book15.webp",
      "../models/boys/salih topcouglu/book/mini/salih book16.webp",
      "../models/boys/salih topcouglu/book/mini/salih book17.webp",
      "../models/boys/salih topcouglu/book/mini/salih book18.webp",
      "../models/boys/salih topcouglu/book/mini/salih book19.webp",
      "../models/boys/salih topcouglu/book/mini/salih book20.webp",
      "../models/boys/salih topcouglu/book/mini/salih book21.webp",
      "../models/boys/salih topcouglu/book/mini/salih book22.webp",
      "../models/boys/salih topcouglu/book/mini/salih book23.webp",
      "../models/boys/salih topcouglu/book/mini/salih book24.webp",
      "../models/boys/salih topcouglu/book/mini/salih book25.webp",
      "../models/boys/salih topcouglu/book/mini/salih book26.webp",
      "../models/boys/salih topcouglu/book/mini/salih book27.webp",
      "../models/boys/salih topcouglu/book/mini/salih book28.webp",
      "../models/boys/salih topcouglu/book/mini/salih book29.webp",
      "../models/boys/salih topcouglu/book/mini/salih book30.webp",
      "../models/boys/salih topcouglu/polas/mini/salih polas.webp",
      //"../models/boys/salih topcouglu/videos/salih_video1.mov",
      //"../models/boys/salih topcouglu/videos/salih_video2.MP4",
      //"../models/boys/salih topcouglu/videos/salih_video3.MP4",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Santiago Poggi - Ceres ===
  {
    name: "Santiago Poggi",
    gender: "Hombres",
    photo: "../models/boys/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
    height: "1.88m",
    measurements: "W 65cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "9/43",
    portfolio: [
      "../models/boys/santiago poggi - ceres/book/mini/1-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/2-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/3-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/4-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/5-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/6-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/7-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/8-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/9-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/10-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/11-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/12-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/13-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/14-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/15-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/16-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/17-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/18-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/19-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/50-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/61-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/30-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/95-santiago-poggi-2025-ceres.webp",
      //"../models/boys/santiago poggi - ceres/videos/santiago_poggi4.mp4",
      //"../models/boys/santiago poggi - ceres/videos/santiago_poggi5.mp4",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Santiago Zezular ===
  {
    name: "Santiago Zezular",
    gender: "Hombres",
    photo: "../models/boys/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
    height: "1.87m",
    measurements: "W 75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "11/45",
    portfolio: [
      "../models/boys/santiago zezular - ceres/book/mini/1-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/2-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/3-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/4-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/5-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/6-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/7-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/8-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/9-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/10-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/11-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/12-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/13-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/14-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/16-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/17-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/18-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/19-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/20-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/21-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/22-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/23-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/24-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/polas/mini/1-santiago-zezular-compolaroid-ceres.webp",
      "../models/boys/santiago zezular - ceres/polas/mini/2-santiago-zezular-compolaroid-ceres.webp",
      //"../models/boys/santiago zezular - ceres/videos/santiago_zezular1.mp4",
      //"../models/boys/santiago zezular - ceres/videos/santiago_zezular2.mp4",

    ],
    instagram: []
  }, // === End Model ===
  // === Model: Maximo ===
  {
    name: "Maximo",
    gender: "Hombres",
    photo: "../models/boys/maximo/book/mini/maximo (1).png",
    height: "1.86m",
    measurements: "W 81cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "43",
    portfolio: [
      "../models/boys/maximo/book/mini/maximo (1).png",
      "../models/boys/maximo/book/mini/maximo (2).png",
      "../models/boys/maximo/book/mini/maximo (3).png",
      "../models/boys/maximo/book/mini/maximo (4).png",
      "../models/boys/maximo/book/mini/maximo (5).png",
      "../models/boys/maximo/book/mini/maximo (6).png",
      "../models/boys/maximo/book/mini/maximo (7).png",
      "../models/boys/maximo/book/mini/maximo (8).png",
      "../models/boys/maximo/book/mini/maximo (9).png",
      "../models/boys/maximo/book/mini/maximo (10).png",
      "../models/boys/maximo/book/mini/maximo (11).png",
      "../models/boys/maximo/videos/maximo_ video.mp4",

    ],
    instagram: []
  }, // === End Model ===

  // === Model: Lucas Terrago ===
  {
    name: "Lucas Terrago",
    gender: "Hombres",
    photo: "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_01.JPG",
    height: "1.82m",
    measurements: "W 76cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/43",
    portfolio: [
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_01.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_02.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_03.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_04.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_05.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_06.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_07.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_08.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_09.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_10.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_11.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_12.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_13.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_14.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_15.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_16.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_17.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_18.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_19.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_20.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_21.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_22.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_23.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_24.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_25.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_26.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_27.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_28.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_29.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_30.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_31.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_32.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_33.jpg",
      "../models/boys/lucas terrago/book/full/lucas_tarrago_book_34.jpg",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_01.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_02.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_03.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_04.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_05.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_06.JPG",
      "../models/boys/lucas terrago/polas/mini/lucas_tarrago_polas_07.JPG",
    ],
    instagram: []
  }, // === End Model ===


  // === Model: Emmanuel ===
  {
    name: "Emmanuel",
    gender: "Hombres",
    photo: "../models/boys/emmanuel/polas/mini/emmanuel_polas (1).jpg",
    height: "1.83m",
    measurements: "36",
    hair: "Brown",
    eyes: "hazel",
    shoe: "8/42",
    portfolio: [
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_01.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_02.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_03.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_04.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_05.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_06.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_07.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_08.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_09.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_10.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_11.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_12.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_13.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_14.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_15.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_16.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_17.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_18.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_19.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_20.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_21.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_22.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_23.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_24.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_25.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_26.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_27.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_28.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_29.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_30.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_31.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_32.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_33.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_34.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_35.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_36.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_37.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_38.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_39.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_40.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_41.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_42.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_43.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_44.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_45.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_46.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_47.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_48.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_49.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_50.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_51.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_52.jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (1).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (10).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (11).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (12).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (13).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (14).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (2).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (3).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (4).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (5).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (6).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (7).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (8).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (9).jpg",
    ],
    instagram: []
  }, // === End Model ===


  // === Model: Mariana Arias ===
  {
    name: "Mariana Arias",
    gender: "Girl",
    photo: "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
    height: "1.75m",
    measurements: "B 75.5cm W 60cm H 88cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "7-38",
    portfolio: [
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_1.webp",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_2.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_3.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_4.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_5.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_6.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_7.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_8.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_9.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_10.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_11.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_12.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_13.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_14.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_15.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_16.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_17.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_18.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_19.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_20.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_21.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_22.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_23.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_24.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_25.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_26.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_27.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_28.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_2.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_3.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_4.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_5.jpg",
      // "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_6.jpg",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_1.mp4",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_2.mp4",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_3.mp4",
    ]
  },

  // === Model: Felicitas Ceres ===
  {
    name: "Felicitas",
    gender: "Girl",
    photo: "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_1.webp",
    height: "1.76m",
    measurements: "B 81cm W 61cm H 96cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39.5",
    portfolio: [
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_1.webp",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_2.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_3.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_4.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_5.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_6.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_7.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_8.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_9.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_10.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_11.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_12.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_13.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_14.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_15.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_16.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_17.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_18.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_19.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_20.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_21.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_22.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_23.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_24.jpg",
      "../models/girls/felicitas - ceres/polas/mini/felicitas_codesal_book_25.jpg",
      //"../models/girls/felicitas - ceres/polas/mini/10-felicitas-codesal-abril-2025-ceres.webp",
      //"../models/girls/felicitas - ceres/polas/mini/18-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/20-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/26-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/31-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/37-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/42-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
    ]

  }, // === End Model ===


  // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Girl",
    photo: "../models/girls/eva - gh/polas/mini/eva digitals 01.webp",
    height: "1.75m",
    measurements: "B 79cm W 59cm H 89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    portfolio: [
      "../models/girls/eva - gh/book/mini/book01.webp",
      "../models/girls/eva - gh/book/mini/book02.webp",
      "../models/girls/eva - gh/book/mini/book03.webp",
      "../models/girls/eva - gh/book/mini/book04.webp",
      "../models/girls/eva - gh/book/mini/book05.webp",
      "../models/girls/eva - gh/book/mini/book06.webp",
      "../models/girls/eva - gh/book/mini/book07.webp",
      "../models/girls/eva - gh/book/mini/book08.webp",
      "../models/girls/eva - gh/book/mini/book09.webp",
      "../models/girls/eva - gh/book/mini/book010.webp",
      "../models/girls/eva - gh/book/mini/book011.webp",
      "../models/girls/eva - gh/book/mini/book013.webp",
      "../models/girls/eva - gh/book/mini/book014.webp",
      "../models/girls/eva - gh/book/mini/book015.webp",
      "../models/girls/eva - gh/book/mini/book016.webp",
      "../models/girls/eva - gh/book/mini/book017.webp",
      "../models/girls/eva - gh/book/mini/book018.webp",
      "../models/girls/eva - gh/book/mini/book019.webp",
      "../models/girls/eva - gh/book/mini/book020.webp",
      "../models/girls/eva - gh/book/mini/book021.webp",
      "../models/girls/eva - gh/book/mini/book022.webp",
      "../models/girls/eva - gh/book/mini/book023.webp",
      "../models/girls/eva - gh/book/mini/book024.webp",
      "../models/girls/eva - gh/book/mini/book025.webp",
      "../models/girls/eva - gh/book/mini/book026.webp",
      "../models/girls/eva - gh/book/mini/book027.webp",
      "../models/girls/eva - gh/book/mini/book028.webp",
      "../models/girls/eva - gh/book/mini/book029.webp",
      "../models/girls/eva - gh/book/mini/book030.webp",
      "../models/girls/eva - gh/book/mini/book031.webp",
      "../models/girls/eva - gh/book/mini/book032.webp",
      "../models/girls/eva - gh/book/mini/book033.webp",
      "../models/girls/eva - gh/book/mini/book034.webp",
      "../models/girls/eva - gh/book/mini/book035.webp",
      "../models/girls/eva - gh/book/mini/book036.webp",
      "../models/girls/eva - gh/book/mini/book037.webp",
      "../models/girls/eva - gh/book/mini/book038.webp",
      "../models/girls/eva - gh/book/mini/book039.webp",
      "../models/girls/eva - gh/book/mini/book040.webp",
      "../models/girls/eva - gh/book/mini/book041.webp",
      "../models/girls/eva - gh/book/mini/book042.webp",
      "../models/girls/eva - gh/book/mini/book043.webp",
      "../models/girls/eva - gh/book/mini/book044.webp",
      "../models/girls/eva - gh/book/mini/book045.webp",
      "../models/girls/eva - gh/book/mini/book046.webp",
      "../models/girls/eva - gh/book/mini/book047.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 01.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 02.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 03.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 04.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 05.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 06.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 07.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 08.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 09.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 10.webp",
      //"../models/girls/eva - gh/videos/eva_video1.mp4",
      //"../models/girls/eva - gh/videos/eva_video2.mp4",
    ]
  },

  // === Model: Emilia ===
  {
    name: "Emilia",
    gender: "Girl",
    photo: "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (1).jpg",
    height: "1.73m",
    measurements: "B 92cm W 60cm H 89cm Dress 2",
    hair: "blonde",
    eyes: "blue",
    shoe: "8/38",
    portfolio: [
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_01.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_02.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_03.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_04.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_05.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_06.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_07.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_08.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_09.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_10.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_11.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_12.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_13.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_14.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_15.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_16.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_17.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_18.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_19.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_20.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_21.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_22.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_23.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_24.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_25.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_26.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_27.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_28.JPG",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_29.JPG",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_30.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_31.jpg",
      "../models/girls/emilia bryan/book/mini/emilia_bryan_book_32.jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (1).jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (2).jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (3).jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (4).jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (5).jpg",
      "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (6).jpg",
    ]
  },

  // === Model: Mafer Bezanilla ===
  {
    name: "Mafer Bezanilla",
    gender: "Girl",
    photo: "../models/girls/mafer bezanilla/polas/mini/mafer_polas (1).JPG",
    height: "1.70m",
    measurements: "B 78cm W 60cm H 88cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6/36",
    portfolio: [
      "../models/girls/mafer bezanilla/book/full/mafer_book_01.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_02.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_03.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_04.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_05.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_06.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_07.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_08.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_09.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_10.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_11.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_12.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_13.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_14.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_15.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_16.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_17.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_18.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_19.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_20.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_21.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_22.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_23.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_24.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_25.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_26.jpg",
      "../models/girls/mafer bezanilla/book/full/mafer_book_27.jpg",
      "../models/girls/mafer bezanilla/polas/full/mafer_polas (1).JPG",
      "../models/girls/mafer bezanilla/polas/full/mafer_polas (2).JPG",
      "../models/girls/mafer bezanilla/polas/full/mafer_polas (3).JPG",
      "../models/girls/mafer bezanilla/polas/full/mafer_polas (4).JPG",
      "../models/girls/mafer bezanilla/polas/full/mafer_polas (5).JPG",
      "../models/girls/mafer bezanilla/polas/mini/mafer_polas (1).JPG",
      "../models/girls/mafer bezanilla/polas/mini/mafer_polas (2).JPG",
      "../models/girls/mafer bezanilla/polas/mini/mafer_polas (3).JPG",
      "../models/girls/mafer bezanilla/polas/mini/mafer_polas (4).JPG",
      "../models/girls/mafer bezanilla/polas/mini/mafer_polas (5).JPG",
    ]
  },
  // === Isabel Deutsch - New Icon ===
  {
    name: "Isabel Deutsch",
    gender: "Girl",
    photo: "../models/girls/isabel deutsch/polas/full/ISABEL-DEUTSCH-POLA-1.jpg",
    height: "1.73m",
    measurements: "B 88cm W 65cm H 90cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "37",
    portfolio: [
      // === Book ===
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-1.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-2.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-3.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-4.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-6.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-8.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-9.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-11.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-13.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-15.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-17.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-19.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-20.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-21.jpg",
      // === Polas ===
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-1.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-2.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-3.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-4.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-5.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-6.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-7.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-8.jpg",
    ],
    instagram: []
    // === End Model ===

  },
  // === Model: Chloe - New Icon ===
  {
    name: "Chloe",
    gender: "Girl",
    photo: "../models/girls/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "1.75m",
    measurements: "B 79cm W 60cm H 89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    portfolio: [
      "../models/girls/chloe - new icon/book/mini/chloe (1).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (2).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (3).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (4).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (5).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (6).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (7).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (8).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (9).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (10).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (11).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (12).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (13).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (14).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (15).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (16).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (17).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (18).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (19).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (20).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (21).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (22).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (23).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (24).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (25).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (26).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (27).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (28).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (29).jpg",
      "../models/girls/chloe - new icon/book/mini/chloe (30).jpg",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola4.webp",
      //"../models/girls/chloe - new icon/videos/Chloe_video.mov",
      //"../models/girls/chloe - new icon/videos/Chloe_video2.mov"
    ],
    instagram: []
    // === End Model ===

  },
];
