const models = [
 
 // === Model: Alicia Vallecilla ===
 /* {
    name: "Alicia Vallecilla",
    gender: "Mujeres",
    photo:  "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__1.webp",
    height: "5'8-1,75m",
    measurements: "B 30-75cm W 23-59cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/39",
    portfolio: [
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_01.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_02.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_03.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_05.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_06.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_07.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_08.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_09.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_10.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_11.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_12.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_13.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_14.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_15.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_16.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_17.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_18.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_19.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_20.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_21.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_22.webp",
        "../models/mujeres/alicia vallecilla - new icon/book/mini/alicia book_23.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__1.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__2.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__3.webp",
        "../models/mujeres/alicia vallecilla - new icon/polas/full/alicia vallecilla__4.webp",
    ]

  },
  */

  // === Model: Audrey Coleman ===
  {
    name: "Audrey Coleman",
    gender: "Mujeres",
    photo: "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__4.webp",
    height: "5'9-1,76m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Light Brown",
    eyes: "Green",
    shoe: "7/38",
    portfolio: [
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 01.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 02.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 03.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 04.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 05.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 06.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 07.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 08.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 09.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 010.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 011.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 012.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 013.webp",
      "../models/mujeres/audrey coleman - new icon/book/mini/audrey book 014.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__1.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__2.webp",
      "../models/mujeres/audrey coleman - new icon/polas/mini/audrey coleman__3.webp",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_01.mp4",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video_02.mp4",
      //"../models/mujeres/audrey coleman - new icon/videos/audrey_coleman_video03.mp4",
    ]
  },

  // === Model: Diana Zenteno ===
  /* {
    name: "Diana Zenteno",
    gender: "Mujeres",
    photo: "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6.5/38",
    portfolio: [
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book1.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book2.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book3.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book4.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book5.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book6.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book7.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book8.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book9.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book10.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book11.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book12.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book13.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book14.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book15.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book16.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book17.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book18.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book19.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book20.webp",
        "../models/mujeres/diana zenteno - new icon/book/mini/diana book21.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__1.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__2.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__3.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__4.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__5.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__6.webp",
      "../models/mujeres/diana zenteno - new icon/polas/mini/diana zenteno__7.webp",
    ]

  },
  */

  // === Model: Felicitas Ceres ===
  {
    name: "Felicitas",
    gender: "Mujeres",
    photo: "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
    height: "5'9.5-1,76m",
    measurements: "B 32-81cm W 24-61cm H 38-96cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39.5",
    portfolio: [
        "../models/mujeres/felicitas - ceres/book/mini/1-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/2-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/3-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/4-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/5-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/6-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/7-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/8-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/9-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/10-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/11-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/12-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/13-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/14-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/15-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/16-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/17-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/18-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/19-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/20-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/21-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/22-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/23-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/book/mini/24-felicitas-codesal-book-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/1-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/10-felicitas-codesal-abril-2025-ceres.webp",
        //"../models/mujeres/felicitas - ceres/polas/mini/18-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/20-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/26-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/31-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/37-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/42-felicitas-codesal-abril-2025-ceres.webp",
        "../models/mujeres/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
    ]

  },

  // === Model: Fema Seimandi ===
  {
    name: "Fema Seimandi",
    gender: "Mujeres",
    photo: "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__1.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "7.5/38.5",
    portfolio: [
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book1.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book2.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book3.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book4.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book5.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book6.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book7.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book8.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book9.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book10.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book11.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book12.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book13.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book14.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book15.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book16.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book17.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book18.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book19.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book20.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book21.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book22.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book23.webp",
        "../models/mujeres/fema seimandi - new icon/book/mini/fema book24.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__1.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__2.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__3.webp",
      "../models/mujeres/fema seimandi - new icon/polas/mini/fema seimandi__4.webp",
    ]

  },

  // === Model: Frida - Ceres ===
  {
    name: "Frida",
    gender: "Mujeres",
    photo: "../models/mujeres/frida - ceres/book/mini/1-frida-richter-main-book-ceres.webp",
    height: "5'9-1,75m",
    measurements: "B 32.5-82cm W 24-61cm H 36-91cm",
    hair: "Dark blond",
    eyes: "Blue",
    shoe: "9/40",
    portfolio: [
        "../models/mujeres/frida - ceres/book/mini/1-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/2-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/3-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/4-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/5-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/6-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/book/mini/7-frida-richter-main-book-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/14-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/15-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/20-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/31-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/55-frida-richter-digitals-25-ceres.webp",
        "../models/mujeres/frida - ceres/polas/mini/62-frida-richter-digitals-25-ceres.webp",
    ]

  },
  // === Model: Genesis - New Icon  ===
  /*{
    name: "Genesis",
    gender: "Mujeres",
    photo: "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
    height: "5'9.5-1,76m",
    measurements: "B 30.5-78cm W 24-60cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8/38",
    portfolio: [
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_01.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_02.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_03.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_04.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_05.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_06.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_07.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_08.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_09.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_10.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_11.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_12.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_13.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_14.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_15.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_16.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_17.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_18.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_19.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_20.webp",
      "../models/mujeres/genesis  - new icon/book/mini/genesis book_21.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas1.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas2.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas3.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas4.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas5.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas6.webp",
      "../models/mujeres/genesis  - new icon/polas/mini/genesis polas7.webp",
    ]

  },
  */

  // === Model: Kass - New Icon ===
  {

    name: "Kass",
    gender: "Mujeres",
    photo: "../models/mujeres/kass - new icon/book/mini/kass__1.webp",
    height: "5'9.5-1,77m",
    measurements: "B 32-80cm W 24-60cm H 35-89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39",
    portfolio: [
      "../models/mujeres/kass - new icon/book/mini/kass__1.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__10.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__11.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__12.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__13.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__14.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__15.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__16.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__17.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__18.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__19.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__2.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__3.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__4.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__5.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__6.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__7.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__8.webp",
      "../models/mujeres/kass - new icon/book/mini/kass__9.webp",
    ]

  },

  // === Model: Luciana Imoberdof - ARG ===
  {
    name: "Luciana Imoberdof",
    gender: "Mujeres",
    photo: "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 01.webp",
    height: "5'10-1,78m",
    measurements: "B 30-76cm W 24-60cm H 35-89cm",
    hair: "Blond",
    eyes: "Blue",
    shoe: "9/39",
    portfolio: [
      // Book
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book01.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book02.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book03.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book04.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book05.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book06.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book07.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book08.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book09.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book10.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book11.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book12.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book13.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book14.webp",
      "../models/mujeres/luciana imoberdof -arg/book/mini/luciana imoberdof book15.webp",
      // Polas
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 01.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 02.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 03.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 06.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 07.webp",
    "../models/mujeres/luciana imoberdof -arg/polas/mini/luciana 10.webp",

    ]

  },

  // === Model: Chloe - New Icon ===
  /* {
    name: "Chloe",
    gender: "Mujeres",
    photo: "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "5'9.5-1,75.5m",
    measurements: "B 31-79cm W 24-60cm H 35-89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    portfolio: [
      "../models/mujeres/chloe - new icon/book/mini/chloe (1).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (2).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (3).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (4).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (5).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (6).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (7).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (8).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (9).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (10).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (11).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (12).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (13).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (14).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (15).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (16).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (17).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (18).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (19).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (20).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (21).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (22).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (23).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (24).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (25).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (26).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (27).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (28).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (29).webp",
      "../models/mujeres/chloe - new icon/book/mini/chloe (30).webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/mujeres/chloe - new icon/polas/mini/chloe bell pola4.webp",
      "../models/mujeres/chloe - new icon/videos/chloe_video (1).mov",
      "../models/mujeres/chloe - new icon/videos/chloe_video (2).mov"
    ]
  },
*/
    // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Mujeres",
    photo: "../models/mujeres/eva - gh/polas/mini/eva digitals 01.webp",
    height: "5'9-1,75m",
    measurements: "B 31-79cm W 23-59cm H 35-89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    portfolio: [
      "../models/mujeres/eva - gh/book/mini/book01.webp",
      "../models/mujeres/eva - gh/book/mini/book02.webp",
      "../models/mujeres/eva - gh/book/mini/book03.webp",
      "../models/mujeres/eva - gh/book/mini/book04.webp",
      "../models/mujeres/eva - gh/book/mini/book05.webp",
      "../models/mujeres/eva - gh/book/mini/book06.webp",
      "../models/mujeres/eva - gh/book/mini/book07.webp",
      "../models/mujeres/eva - gh/book/mini/book08.webp",
      "../models/mujeres/eva - gh/book/mini/book09.webp",
      "../models/mujeres/eva - gh/book/mini/book010.webp",
      "../models/mujeres/eva - gh/book/mini/book011.webp",
      "../models/mujeres/eva - gh/book/mini/book013.webp",
      "../models/mujeres/eva - gh/book/mini/book014.webp",
      "../models/mujeres/eva - gh/book/mini/book015.webp",
      "../models/mujeres/eva - gh/book/mini/book016.webp",
      "../models/mujeres/eva - gh/book/mini/book017.webp",
      "../models/mujeres/eva - gh/book/mini/book018.webp",
      "../models/mujeres/eva - gh/book/mini/book019.webp",
      "../models/mujeres/eva - gh/book/mini/book020.webp",
      "../models/mujeres/eva - gh/book/mini/book021.webp",
      "../models/mujeres/eva - gh/book/mini/book022.webp",
      "../models/mujeres/eva - gh/book/mini/book023.webp",
      "../models/mujeres/eva - gh/book/mini/book024.webp",
      "../models/mujeres/eva - gh/book/mini/book025.webp",
      "../models/mujeres/eva - gh/book/mini/book026.webp",
      "../models/mujeres/eva - gh/book/mini/book027.webp",
      "../models/mujeres/eva - gh/book/mini/book028.webp",
      "../models/mujeres/eva - gh/book/mini/book029.webp",
      "../models/mujeres/eva - gh/book/mini/book030.webp",
      "../models/mujeres/eva - gh/book/mini/book031.webp",
      "../models/mujeres/eva - gh/book/mini/book032.webp",
      "../models/mujeres/eva - gh/book/mini/book033.webp",
      "../models/mujeres/eva - gh/book/mini/book034.webp",
      "../models/mujeres/eva - gh/book/mini/book035.webp",
      "../models/mujeres/eva - gh/book/mini/book036.webp",
      "../models/mujeres/eva - gh/book/mini/book037.webp",
      "../models/mujeres/eva - gh/book/mini/book038.webp",
      "../models/mujeres/eva - gh/book/mini/book039.webp",
      "../models/mujeres/eva - gh/book/mini/book040.webp",
      "../models/mujeres/eva - gh/book/mini/book041.webp",
      "../models/mujeres/eva - gh/book/mini/book042.webp",
      "../models/mujeres/eva - gh/book/mini/book043.webp",
      "../models/mujeres/eva - gh/book/mini/book044.webp",
      "../models/mujeres/eva - gh/book/mini/book045.webp",
      "../models/mujeres/eva - gh/book/mini/book046.webp",
      "../models/mujeres/eva - gh/book/mini/book047.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 01.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 02.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 03.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 04.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 05.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 06.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 07.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 08.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 09.webp",
      "../models/mujeres/eva - gh/polas/full/eva digitals 10.webp",
      //"../models/mujeres/eva - gh/videos/eva_video1.mp4",
      //"../models/mujeres/eva - gh/videos/eva_video2.mp4",
    ]
  },


  // === Model: ADAN - NEW ICON === 
  {
    name: "Adan",
    gender: "Hombres",
    photo: "../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
    height: "6'1-1,85m",
    measurements: "W 30-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8/42",
    portfolio: [
      "../models/hombres/adan - new icon/book/full/adan book_01.webp",
      "../models/hombres/adan - new icon/book/full/adan book_02.webp",
      "../models/hombres/adan - new icon/book/full/adan book_03.webp",
      "../models/hombres/adan - new icon/book/full/adan book_04.webp",
      "../models/hombres/adan - new icon/book/full/adan book_05.webp",
      "../models/hombres/adan - new icon/book/full/adan book_06.webp",
      "../models/hombres/adan - new icon/book/full/adan book_07.webp",
      "../models/hombres/adan - new icon/book/full/adan book_08.webp",
      "../models/hombres/adan - new icon/book/full/adan book_09.webp",
      "../models/hombres/adan - new icon/book/full/adan book_10.webp",
      "../models/hombres/adan - new icon/book/full/adan book_11.webp",
      "../models/hombres/adan - new icon/book/full/adan book_12.webp",
      "../models/hombres/adan - new icon/book/full/adan book_13.webp",
      "../models/hombres/adan - new icon/book/full/adan book_14.webp",
      "../models/hombres/adan - new icon/book/full/adan book_15.webp",
      "../models/hombres/adan - new icon/book/full/adan book_16.webp",
      "../models/hombres/adan - new icon/book/full/adan book_17.webp",
      "../models/hombres/adan - new icon/book/full/adan book_18.webp",
      "../models/hombres/adan - new icon/book/full/adan book_19.webp",
      "../models/hombres/adan - new icon/book/full/adan book_20.webp",
      "../models/hombres/adan - new icon/book/full/adan book_21.webp",
      "../models/hombres/adan - new icon/book/full/adan book_22.webp",
      "../models/hombres/adan - new icon/book/full/adan book_23.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas 1.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas2.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas3.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas4.webp",
      //"../models/hombres/adan - new icon/polas/full/adan_polas5.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan6.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan7.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan8.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan9.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan10.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan11.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan12.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan13.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan14.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan15.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan16.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan17.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan18.webp",
      "../models/hombres/adan - new icon/polas/full/polas_adan19.webp",
      //"../models/hombres/adan - new icon/polas/full/polas_adan20.webp",
      "../models/hombres/adan - new icon/polas/full/adan_polas21.webp",
      //"../models/hombres/adan - new icon/videos/video_adan_1.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_2.mp4",
      // "../models/hombres/adan - new icon/videos/video_adan_3.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_4.mp4",
      //"../models/hombres/adan - new icon/videos/video_adan_5.mp4",

      
    ],
    instagram: []
  }, // === End Model ===

  // === Model: AGUSTIN BEJOS - NEW ICON ===
  {
    name: "Agustin",
    gender: "Hombres",
    photo: "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__1.webp",
    height: "6'2-1,88m",
    measurements: "W 32.5-81cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "8.5/42",
    portfolio: [
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book1.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book2.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book3.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book4.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book5.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book6.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book7.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book8.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book9.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book10.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book11.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book12.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book13.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book14.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book15.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book16.webp",
      "../models/hombres/agustin bejos - new icon/book/mini/agustin b book17.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__1.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__2.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__3.webp",
      "../models/hombres/agustin bejos - new icon/polas/mini/agustin bejos__4.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: ANGEL BRETT - NEW ICON ===
  {
    name: "Angel",
    gender: "Hombres",
    photo: "../models/hombres/angel brett - new icon/polas/mini/angel bret__1.webp",
    height: "6'1-1,85m",
    measurements: "31-74cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/42",
    portfolio: [
      "../models/hombres/angel brett - new icon/book/mini/angel bret book1.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book2.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book3.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book4.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book5.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book6.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book7.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book8.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book9.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book10.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book11.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book12.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book13.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book14.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book15.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book16.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book17.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book18.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book19.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book20.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book21.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book22.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book23.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book24.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book25.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book26.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book27.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book28.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book29.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book30.webp",
      "../models/hombres/angel brett - new icon/book/mini/angel bret book31.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__2.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__3.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__4.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__5.webp",
      "../models/hombres/angel brett - new icon/polas/mini/angel bret__6.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: JORGE TIRADO -BLINK ===
  {
    name: "Jorge Tirado",
    gender: "Hombres",
    photo: "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_4.webp",
    height: "6'2-1,87m",
    measurements: "W 30-72cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "10.5/44",
    portfolio: [
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book1.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book2.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book3.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book4.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book5.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book6.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book7.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book8.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book9.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book10.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book11.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book13.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book14.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book15.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book16.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book17.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book18.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book22.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book20.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book21.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book19.webp",
    "../models/hombres/jorge tirado-blink/book/mini/jorge tirado book23.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_1.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_2.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_3.webp",
    "../models/hombres/jorge tirado-blink/polas/webp/jorge tirado polas_4.webp",
    
    ],
    instagram: []
  }, // === End Model ===

  // === Model: JOSEPH BIZARRO ' BLINK ===
  {
    name: "Joseph Bizarro",
    gender: "Hombres",
    photo: "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__1.webp",
    height: "6'1-1,85m",
    measurements: "W 32-80cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "43",
    portfolio: [
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__1.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__2.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__3.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__4.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__5.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__6.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__7.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__8.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__9.webp",
      "../models/hombres/joseph bizarro - blink/book/full/joseph bizarro__10.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Kevin Rodriguez - Ceres ===
  {
    name: "Kevin Rodriguez",
    gender: "Hombres",
    photo: "../models/hombres/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    height: "6'2-1,88m",
    measurements: "W 30.5-77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/44",
    portfolio: [
      "../models/hombres/kevin rodriguez - ceres/book/mini/1-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/2-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/3-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/4-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/5-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/6-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/7-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/8-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/9-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/10-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/11-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/12-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/13-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/14-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/15-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/16-kevin-rodriguez-main-book-ceres.webp",
      "../models/hombres/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: ROBBY POWERS - NEW ICON ===
  {
    name: "Robby Powers",
    gender: "Hombres",
    photo: "../models/hombres/robby powers - new icon/book/mini/robby powers__1.webp",
    height: "6'2-1,87.5m",
    measurements: "W 31-79cm",
    hair: "Brown",
    eyes: "Blue",
    shoe: "11.5/43",
    portfolio: [
      "../models/hombres/robby powers - new icon/book/mini/robby powers__1.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__2.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__3.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__4.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__5.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__6.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__7.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__8.webp",
      "../models/hombres/robby powers - new icon/book/mini/robby powers__9.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_1.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_2.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_3.webp",
      "../models/hombres/robby powers - new icon/polas/mini/ROBBY POWERS - NEW ICON Polas_4.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Salih Topcouglu ===
  /* {
    name: "Salih",
    gender: "Hombres",
    photo: "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
    height: "6'2-1,88m",
    measurements: "W 30.5-77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/43",
    portfolio: [
      "../models/hombres/salih topcouglu/book/mini/salih book1.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book2.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book3.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book4.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book5.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book6.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book7.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book8.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book9.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book10.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book11.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book12.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book13.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book14.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book15.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book16.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book17.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book18.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book19.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book20.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book21.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book22.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book23.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book24.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book25.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book26.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book27.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book28.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book29.webp",
      "../models/hombres/salih topcouglu/book/mini/salih book30.webp",
      "../models/hombres/salih topcouglu/polas/mini/salih polas.webp",
      //"../models/hombres/salih topcouglu/videos/salih_video1.mov",
      //"../models/hombres/salih topcouglu/videos/salih_video2.MP4",
      //"../models/hombres/salih topcouglu/videos/salih_video3.MP4",
    ],
    instagram: []
  }, // === End Model ===
*/
  // === Model: Santiago Poggi - Ceres ===
  {
    name: "Santiago Poggi",
    gender: "Hombres",
    photo: "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
    height: "6'2-1,88m",
    measurements: "W 26-65cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "9/43",
    portfolio: [
      "../models/hombres/santiago poggi - ceres/book/mini/1-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/2-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/3-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/4-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/5-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/6-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/7-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/8-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/9-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/10-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/11-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/12-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/13-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/14-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/15-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/16-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/17-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/18-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/19-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/50-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/61-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/30-santiago-poggi-2025-ceres.webp",
      "../models/hombres/santiago poggi - ceres/book/mini/95-santiago-poggi-2025-ceres.webp",
      //"../models/hombres/santiago poggi - ceres/videos/santiago_poggi4.mp4",
      //"../models/hombres/santiago poggi - ceres/videos/santiago_poggi5.mp4",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Santiago Zezular ===
  {
    name: "Santiago Zezular",
    gender: "Hombres",
    photo: "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
    height: "6'1.5-1,87m",
    measurements: "W 29.5-75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "11/45",
    portfolio: [
      "../models/hombres/santiago zezular - ceres/book/mini/1-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/2-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/3-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/4-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/5-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/6-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/7-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/8-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/9-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/10-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/11-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/12-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/13-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/14-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/16-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/17-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/18-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/19-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/20-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/21-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/22-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/23-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/book/mini/24-santiago-zezular-main-book-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/1-santiago-zezular-compolaroid-ceres.webp",
      "../models/hombres/santiago zezular - ceres/polas/mini/2-santiago-zezular-compolaroid-ceres.webp",
      //"../models/hombres/santiago zezular - ceres/videos/santiago_zezular1.mp4",
      //"../models/hombres/santiago zezular - ceres/videos/santiago_zezular2.mp4",

    ],
    instagram: []
  }, // === End Model ===
];